using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Monkestation.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminInternetSoundWindow : DefaultWindow
    {
        public AdminInternetSoundWindow()
        {
            RobustXamlLoader.Load(this);
            PlayButton.OnPressed += OnPlayPressed;
            StopButton.OnPressed += OnStopPressed;
        }

        private void OnPlayPressed(BaseButton.ButtonEventArgs args)
        {

        }

        private void OnStopPressed(BaseButton.ButtonEventArgs args)
        {

        }
    }
}
