using Content.Shared._Monkestation.Audio.ICassettes;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Monkestation.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminInternetSoundWindow : DefaultWindow
    {
        [Dependency] private readonly IPlayerManager _playerMan = default!;
        public AdminInternetSoundWindow()
        {
            RobustXamlLoader.Load(this);
            PlayButton.OnPressed += OnPlayPressed;
            StopButton.OnPressed += OnStopPressed;
        }

        private void OnPlayPressed(BaseButton.ButtonEventArgs args)
        {
            var netMan = IoCManager.Resolve<IEntityNetworkManager>();
            var player = _playerMan.LocalSession;
            if (player == null)
            {
                Logger.Warning("No local session no found");
                return;
            }

            var ev = new ISharedCassetteSystem.CassetteActionEvent(player.UserId, player.Name, "Play");
            netMan.SendSystemNetworkMessage(ev);
        }

        private void OnStopPressed(BaseButton.ButtonEventArgs args)
        {

        }
    }
}
